config/routes.rb
FusionApp::Application.routes.draw do
  resources :attendances


  resources :youths



  get "attendances/welcome"

  root :to => "attendances#index"
  
  resources :courses


  authenticated :user do
  root :to => "attendances#index"
  end
 
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="masthead">
	<br>
	   <%= link_to image_tag("logo.png"), root_path, :class=>' nav pull-left'%>	




<ul class="nav pull-right">

 <% if user_signed_in? %>
  
 <li>
		<%= link_to attendances_path, :class => 'btn btn-custom spacer' do %>
		Attendance <i class="icon-plus-sign"></i>
		<% end %>&nbsp; &nbsp;
    </li>

<li>

		<%= link_to youths_path, :class => 'btn btn-custom  spacer' do %>
		Youth <i class="icon-user"></i>
		<% end %>

    </li>

 <li>
		<%= link_to courses_path, :class => 'btn btn-custom spacer' do %>
		Programs <i class="icon-star"></i>
		<% end %>
		
    </li>

 
    <li>
  

		<%= link_to destroy_user_session_path, :method=>'delete', :class => 'btn btn-custom spacer' do %>
		Logout 
		<% end %>

    </li>
  <% else %>
    <li>
	<%= link_to new_user_session_path, :class => 'btn btn-custom spacer' do %>
	Login 
	<% end %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>

	<%= link_to edit_user_registration_path, :class => 'btn btn-custom spacer' do %>
	Edit account
	<% end %>

    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path,  :class => 'btn btn-custom spacer'%>
      </li>
    <% end %>
  <% else %>

  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fusion Stat Tracker" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fusion Stat Tracker" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>